#!/bin/bash

if [ -f version ]; then
    current_version=$(cat version)
else
    current_version=0
fi

current_version=$(echo "$current_version" | tr -d '[:space:]')

new_version=$((current_version + 1))

echo "$new_version" > version

hex_version=$(printf "%x" "$new_version")

git add .
git commit -m "c$hex_version"
